In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/archive (2).zip')
df

Unnamed: 0       Make      Model  Year  Mileage  Condition     Price
0             0       Ford  Silverado  2022    18107  Excellent  19094.75
1             1     Toyota  Silverado  2014    13578  Excellent  27321.10
2             2  Chevrolet      Civic  2016    46054       Good  23697.30
3             3       Ford      Civic  2022    34981  Excellent  18251.05
4             4  Chevrolet      Civic  2019    63565  Excellent  19821.85
..          ...        ...        ...   ...      ...        ...       ...
995         995     Nissan      Camry  2010   149032  Excellent  24548.50
996         996  Chevrolet      F-150  2014    20608  Excellent  26969.70
997         997       Ford     Altima  2016   109851       Good  20507.55
998         998     Toyota  Silverado  2010    11704       Good  31414.90
999         999     Nissan  Silverado  2017   128390  Excellent  18580.60

[1000 rows x 7 columns]

In [ ]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df

Make      Model  Year  Mileage  Condition     Price
0         Ford  Silverado  2022    18107  Excellent  19094.75
1       Toyota  Silverado  2014    13578  Excellent  27321.10
2    Chevrolet      Civic  2016    46054       Good  23697.30
3         Ford      Civic  2022    34981  Excellent  18251.05
4    Chevrolet      Civic  2019    63565  Excellent  19821.85
..         ...        ...   ...      ...        ...       ...
995     Nissan      Camry  2010   149032  Excellent  24548.50
996  Chevrolet      F-150  2014    20608  Excellent  26969.70
997       Ford     Altima  2016   109851       Good  20507.55
998     Toyota  Silverado  2010    11704       Good  31414.90
999     Nissan  Silverado  2017   128390  Excellent  18580.60

[1000 rows x 6 columns]

In [ ]:
df.dtypes

Make          object
Model         object
Year           int64
Mileage        int64
Condition     object
Price        float64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
for column in df.select_dtypes(include='object'):
  df[column]=lb.fit_transform(df[column])
df


Make  Model  Year  Mileage  Condition     Price
0       1      4  2022    18107          0  19094.75
1       4      4  2014    13578          0  27321.10
2       0      2  2016    46054          2  23697.30
3       1      2  2022    34981          0  18251.05
4       0      2  2019    63565          0  19821.85
..    ...    ...   ...      ...        ...       ...
995     3      1  2010   149032          0  24548.50
996     0      3  2014    20608          0  26969.70
997     1      0  2016   109851          2  20507.55
998     4      4  2010    11704          2  31414.90
999     3      4  2017   128390          0  18580.60

[1000 rows x 6 columns]

In [ ]:
df.dtypes

Make           int64
Model          int64
Year           int64
Mileage        int64
Condition      int64
Price        float64
dtype: object

In [ ]:
df.isna().sum()

Make         0
Model        0
Year         0
Mileage      0
Condition    0
Price        0
dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
x

array([[     1,      4,   2022,  18107,      0],
       [     4,      4,   2014,  13578,      0],
       [     0,      2,   2016,  46054,      2],
       ...,
       [     1,      0,   2016, 109851,      2],
       [     4,      4,   2010,  11704,      2],
       [     3,      4,   2017, 128390,      0]])

In [ ]:
y=df.iloc[:,-1].values
y

array([19094.75, 27321.1 , 23697.3 , 18251.05, 19821.85, 27820.  ,
       27426.6 , 22526.55, 21935.1 , 20465.45, 17365.45, 20904.4 ,
       26005.  , 16125.65, 24351.3 , 17968.35, 22586.05, 20347.4 ,
       25927.8 , 25916.4 , 20680.35, 15010.8 , 20565.15, 16966.65,
       28652.45, 21722.15, 20544.55, 25218.55, 18296.  , 24266.5 ,
       28285.25, 18965.45, 28813.1 , 17124.95, 20926.8 , 23683.4 ,
       19810.75, 23894.1 , 24189.9 , 16318.75, 15400.4 , 18064.85,
       14002.85, 22544.7 , 30142.65, 26341.85, 26717.55, 24379.6 ,
       23558.35, 19133.5 , 25805.7 , 21988.2 , 19159.15, 22756.1 ,
       22145.85, 29321.65, 28179.8 , 18901.5 , 19457.8 , 26409.65,
       31034.15, 19272.9 , 22175.45, 25024.7 , 28067.75, 18802.1 ,
       18383.1 , 24568.15, 25184.35, 24886.  , 25203.5 , 21156.45,
       27647.35, 19691.75, 19000.55, 18240.3 , 22844.3 , 20688.2 ,
       24762.45, 19949.9 , 24624.45, 21275.6 , 15725.45, 26081.2 ,
       23028.65, 20010.  , 22944.45, 23669.  , 20031.9 , 19910

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[     3,      3,   2010,  42099,      2],
       [     4,      1,   2010, 124705,      0],
       [     0,      3,   2014,  33760,      2],
       ...,
       [     2,      2,   2014,  10120,      0],
       [     0,      3,   2021, 102564,      0],
       [     3,      3,   2017,  50778,      0]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_train


array([[ 6.95979392e-01,  7.66095588e-01, -1.56239708e+00,
        -9.02501309e-01,  1.46586351e+00],
       [ 1.39295446e+00, -6.16035628e-01, -1.56239708e+00,
         1.18108312e+00, -7.81900909e-01],
       [-1.39494582e+00,  7.66095588e-01, -5.06978064e-01,
        -1.11283725e+00,  1.46586351e+00],
       ...,
       [-9.95678673e-04,  7.50299803e-02, -5.06978064e-01,
        -1.70911277e+00, -7.81900909e-01],
       [-1.39494582e+00,  7.66095588e-01,  1.34000522e+00,
         6.22617116e-01, -7.81900909e-01],
       [ 6.95979392e-01,  7.66095588e-01,  2.84586199e-01,
        -6.83589496e-01, -7.81900909e-01]])

In [ ]:
x_test=scaler.transform(x_test)
x_test

array([[ 1.39295446e+00, -1.30710124e+00, -1.56239708e+00,
        -1.21294797e+00, -7.81900909e-01],
       [ 1.39295446e+00,  7.66095588e-01, -2.43123309e-01,
        -6.97487457e-01,  3.41981301e-01],
       [ 6.95979392e-01,  7.66095588e-01, -1.29854233e+00,
        -1.68961527e+00, -7.81900909e-01],
       ...,
       [-9.95678673e-04, -1.30710124e+00, -1.29854233e+00,
        -4.97316452e-01,  1.46586351e+00],
       [-1.39494582e+00,  1.45716120e+00, -2.43123309e-01,
         2.92370270e-01,  1.46586351e+00],
       [-1.39494582e+00, -1.30710124e+00, -7.70832818e-01,
         1.21980067e+00, -7.81900909e-01]])

In [ ]:
from sklearn.neighbors  import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
model=SVC()
lst=[knn,base,model]


In [ ]:
y_train=lb.fit_transform(y_train)
y_test = lb.fit_transform(y_test)

In [ ]:
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("Model is",i)
  print(y_pred)
  print("*"*100)
  print("score is",accuracy_score(y_test,y_pred))
  print("*"*100)
  print("confusion matrix is",confusion_matrix(y_test,y_pred))
  print("*"*100)
  print("classification report is",classification_report(y_test,y_pred))

Model is KNeighborsClassifier(n_neighbors=7)
[628 248 609 429 244 430 597 570 237 221   0 271 338 162 437 543 103  28
 401 594 277 233 164 345 349   7 110 211  69 135 139 133   9 109 140 231
 369 200 561 395 380 342  65 410 286 302  99  69  26  88  11   3  66 275
  26 493 303  45  11   6 214 213  94 141 270   6  78 594 331 390 457  78
 271 178 183 553  73  14 260  16 337  92 288 312 246 157 554 392 348 555
 152 190 261   0 449 400   6  85 421 418 338 607 171   3 329 141 154 364
  42 100 140   2 130 543 187 483  14 117 425 466 245 457 202 488 300  21
 584 158 527 424 596 150  20 334 465 596 110 349 179 483 553 165  79 388
 160 640 514  47  63 189 335 148 349  78   8 160  37 125 547 125 349 139
 367   2  88 513   7  78 211 418 149 430  65  31   0 210 480 378 342 457
  69  11   0 473 423  18 567 300 448  38 276 211   6   0 613 174  14 450
 141 429 377 360 349 428 532 133 174  19 264 607 100 432 638  41  47  28
 232 335 128 432 140 121 301 143 527 278 122  81 342 373 508 312 115   3
  37 1

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

Model is SVC()
[619 567 619 558 278 619 687 619 278 278 278 619 619 278 278 684 278 278
 616 619 278 278 278 278 522  12 170 619 278 278 278 278 278 278 619 278
 619 278 619 619 566 619 170 278 278 278 278  69 278 278 278 278 213 619
 278 619 278 278 278  53 619 304 170 170 278  57 130 619 278 390 618 278
 619 278 170 675 278 278 170 278 278 278 554 619 278 278 684 278 663 619
 278 278 619 278 619 278  53 278 278 548 278 619 278 278 478 170 243 278
  79 278 619 278 170 278 458 278 278 278 618 619 278 618 462 546 619 105
 619 278 619 500 619 278 278 278 619 619 278 278 170 550 684 278 278 278
 170 619 619 170 278 619 278 151 556 170   8 170 236 278 619 278 522 278
 566   4 278 619  52 170 619 580 243 619 278 278   0 377 278 619 278 618
 390 278 278 691 619 278 605 278 562 278 619 170  69 278 619 170 278 624
 278 468 278 619 278 278 619 278 170 278 458 619 278 614 619 278 170 278
 278 278 278 519 170 278 278 170 619 278 278 170 619 619 619 619 170 278
  86 131 278 619 468 278 170 118 278

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.